name: Use shared composite
on:
  workflow_call:
    inputs:
      who:
        description: Who to say hello to using shared composite action
        required: true
        type: string

jobs:
  say_hello:
    name: Use Composite action
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub Context
        run: echo "${{ toJson(github) }}"
    
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            actions
          repository: "patrikpolyak-ghec-kiwike-org/composite-workflow"
          ref: "v1"

      - uses: "./actions/shared"
        with:
          who: ${{inputs.who}}
